import "@/styles/globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import { inter, urbanist } from "@/config/fonts";
import { Providers } from "@/config/providers";

export const metadata = {
  title: "Cinematic",
  description: "Generated by create next app",
};

export default function RootLayout({ children, trailerModal }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${urbanist.variable} antialiased bg-black`}
      >
        <Providers>
          {children} {trailerModal}
        </Providers>
      </body>
    </html>
  );
}
